export const cities = [
  { value: "Ariyalur", label: "Ariyalur" },
  { value: "Chennai", label: "Chennai" },
  { value: "Coimbatore", label: "Coimbatore" },
  { value: "Cuddalore", label: "Cuddalore" },
  { value: "Dharmapuri", label: "Dharmapuri" },
  { value: "Dindigul", label: "Dindigul" },
  { value: "Erode", label: "Erode" },
  { value: "Kallakurichi", label: "Kallakurichi" },
  { value: "Kancheepuram", label: "Kancheepuram" },
  { value: "Kanniyakumari", label: "Kanniyakumari" },
  { value: "Karur", label: "Karur" },
  { value: "Krishnagiri", label: "Krishnagiri" },
  { value: "Madurai", label: "Madurai" },
  { value: "Nagapattinam", label: "Nagapattinam" },
  { value: "Namakkal", label: "Namakkal" },
  { value: "Nilgiris", label: "Nilgiris" },
  { value: "Perambalur", label: "Perambalur" },
  { value: "Pudukkottai", label: "Pudukkottai" },
  { value: "Ramanathapuram", label: "Ramanathapuram" },
  { value: "Ranipet", label: "Ranipet" },
  { value: "Salem", label: "Salem" },
  { value: "Sivaganga", label: "Sivaganga" },
  { value: "Tenkasi", label: "Tenkasi" },
  { value: "Thanjavur", label: "Thanjavur" },
  { value: "Theni", label: "Theni" },
  { value: "Thoothukudi", label: "Thoothukudi" },
  { value: "Tiruchirappalli", label: "Tiruchirappalli" },
  { value: "Tirunelveli", label: "Tirunelveli" },
  { value: "Tirupathur", label: "Tirupathur" },
  { value: "Tiruppur", label: "Tiruppur" },
  { value: "Tiruvallur", label: "Tiruvallur" },
  { value: "Tiruvannamalai", label: "Tiruvannamalai" },
  { value: "Tiruvarur", label: "Tiruvarur" },
  { value: "Vellore", label: "Vellore" },
  { value: "Viluppuram", label: "Viluppuram" },
  { value: "Virudhunagar", label: "Virudhunagar" },
];
export const states = [
  { value: "Andhra Pradesh", label: "Andhra Pradesh" },
  { value: "Arunachal Pradesh", label: "Arunachal Pradesh" },
  { value: "Assam", label: "Assam" },
  { value: "Bihar", label: "Bihar" },
  { value: "Chhattisgarh", label: "Chhattisgarh" },
  { value: "Goa", label: "Goa" },
  { value: "Gujarat", label: "Gujarat" },
  { value: "Haryana", label: "Haryana" },
  { value: "Himachal Pradesh", label: "Himachal Pradesh" },
  { value: "Jharkhand", label: "Jharkhand" },
  { value: "Karnataka", label: "Karnataka" },
  { value: "Kerala", label: "Kerala" },
  { value: "Madhya Pradesh", label: "Madhya Pradesh" },
  { value: "Maharashtra", label: "Maharashtra" },
  { value: "Manipur", label: "Manipur" },
  { value: "Meghalaya", label: "Meghalaya" },
  { value: "Mizoram", label: "Mizoram" },
  { value: "Nagaland", label: "Nagaland" },
  { value: "Odisha", label: "Odisha" },
  { value: "Punjab", label: "Punjab" },
  { value: "Rajasthan", label: "Rajasthan" },
  { value: "Sikkim", label: "Sikkim" },
  { value: "Tamil Nadu", label: "Tamil Nadu" },
  { value: "Telangana", label: "Telangana" },
  { value: "Tripura", label: "Tripura" },
  { value: "Uttar Pradesh", label: "Uttar Pradesh" },
  { value: "Uttarakhand", label: "Uttarakhand" },
  { value: "West Bengal", label: "West Bengal" },
];
